### ISSUE TITLE
I am trying to extract sound files from sonic and the black knight but every adx file I convert has static and I don't know why.

### ISSUE THREAD

**Issue by F3arM3** [OSA413/FFmpeg-based-ADX-converter#1]
**VOLUME WARNING**
[Bad file.zip](https://github.com/OSA413/FFmpeg-based-ADX-converter/files/8985938/Bad.file.zip)
I included the original file and the flac that I converted it to.

**Comment by OSA413** [comment]
I'm afraid that this issue is not related to the converter since I tried three other ADX converters and they all produced the same distorted sound.
The problem may be in the tool that you use for file extraction.
